website/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name = 'home'),
    # path('login/', views.loginform.as_view(), name = 'login'),
    path('login/', views.logins, name = 'login'),
    path('logup/', views.post, name = 'logup'),
    path('shop/', views.shop, name = 'shop'),
    path('single/<str:pk>/', views.single, name= 'single'),
    path('cart/<str:pk>/', views.cart, name = 'cart'),
    path('search', views.search, name = 'search'),
    path('remove/<str:pk>/', views.remove_from_cart, name = 'remove'),
    path('outs', views.out, name = 'outs'),
    path('order/<str:pk>/', views.orders, name = 'order'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/home/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.
class fileupload(models.Model):
    title = models.CharField(max_length=200)
    image = models.FileField()
    body = models.TextField()
    soluong = models.FloatField()
    giaca = models.FloatField()
    def __str__(self):
        return self.title
class product(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=200)
    price = models.FloatField()
    # descripyion = models.TextField()
    def __str__(self):
        return self.name
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class cart(models.Model):
    ImageField = models.ImageField(null=True, blank=True)
    name = models.CharField(max_length=200)
    price = models.FloatField()
    number = models.CharField(max_length=12)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    product = models.ForeignKey(product, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField(default = 1)
    def __str__(self):
        return f"{self.quantity} x {self.product.product_id}"
class orders(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=200)
    product = models.ForeignKey(product, on_delete = models.SET_NULL, null=True, blank=False)
    def __str__(self):
        return self.name

website/home/forms.py
from django import forms
class signUpForm(forms.Form):
    username = forms.CharField(max_length=50)
    email = forms.EmailField()
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)
class loginform(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

website/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import loginform, signUpForm
from django.views import View, generic
from .models import product, cart, fileupload, orders
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
def home(request):
    products = product.objects.all()
    return render(request, 'home/index.html', {'products':products})
# class loginform(View):
#     def login(self, request):
#         cF = loginform
#         return render(request, 'home/login.html', {'cF':cF})
#     def post(self, request):
#         user = request.POST['username']
#         password = request.POST['password']
#         if(user is not None):
#             login(request, user)
#             return render(request, 'home/login.html')
#         else:
#             return render(request, 'home/index.html')

def logins(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'home/index.html')
            if is_superuser == 1:
                return render(request, 'http://127.0.0.1:8000/admin/')
            else:
                return render(request, 'home/index.html')
        else:
            error_message = 'Invalid login credentials. Please try again.'
            return render(request, 'home/login.html', {'error_message': error_message})
    else:
        success_message = 'Đăng nhập thành công'
        return render(request, 'home/login.html', {'success_message': success_message})

def post(request):
    # return render(request, 'home/signup.html')
    if request.method == 'POST':
        username = request.POST['username'] # truyền thông tin theo phương thức post
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email ,password)
        user.save()
        return render(request, 'home/login.html')
    else:
        return render(request, 'home/signup.html')
def shop(request):
    products = product.objects.all()
    return render(request, 'home/shop.html', {'products':products})
def single(request, pk):
    produc = product.objects.get(id = pk)
    
    return render(request, 'home/shop-single.html', {'produc':produc})

def cart(request, pk):
    # product = product.objects.get(id = product_id)
    # cart = request.sessions.get('cart', {})
    # cart[product_id] = {
    #     'id': product_id,
    #     'name': product.name,
    #     'price': str(product.price),
    #     'quantity': 1,
    #     'image': product.image.url
    # }
    # request.sessions['cart'] = cart
    carts = product.objects.get(id = pk)
    # cartd = cart(request)
    if request.method == 'POST':
        image = item['ImageField']
        name = item['name']
        price = item['price']
        number = item['number']
        cartd = cart.objects.create(ImageField, name, price, number)
        cartd.save()
    carts.save()
    # cart = cart(request)
    

    # def map_function(p):
    #     pid = str(p.id)
    #     q = cart.cart[pid]['quantity']
    #     return {'product': p, 'quantity': q, 'total': p.price*q, 'form': CartForm(initial={'quantity': q, 'product_id': pid})}

    # cart_items = map(map_function, product)
    # return render(request, 'cart/cart_details.html', {'cart_items': cart_items, 'total': cart.get_total_price()})

    # if request.method == 'POST':
    #    form = cart(request.POST)
    #    if form.is_valid():
    #         form.save()
     # Lấy sản phẩm dựa trên id
    # productd = get_object_or_404(product,id = pk)
    # Lấy giỏ hàng hiện tại của người dùng hoặc tạo một giỏ hàng mới nếu người dùng chưa có giỏ hàng
    # if request.method == 'POST':
    #     carts = cart(request.POST)
    #     if carts.is_valid():
        # Thêm sản phẩm vào giỏ hàng
            # carts.add(cart=productd)
            # def add(product):
            #     product_id = str(product.id)
            #     if product_id not in carts:
            #         cart[product_id] = {'quantity': 0, 'price': str(product.price)}
            #         cart[product_id]['quantity'] += 1
            #         carts.save()
        # Chuyển hướng đến trang giỏ hàng
    return render(request, 'home/cart.html', {'carts':carts})
            # return redirect('home')
# def clear():
#         # Xóa giỏ hàng khỏi session
#     del session[settings.CART_SESSION_ID]
#     session.modified = True
    # try:
    #     carts = cart.objects.get(user = request.user, product = product)
    #     carts.quantity +=1
    #     carts.save()
    # except cart.DoesNotExist:
    #     cart = cart.objects.create(user = request.user, product = product)
    # return render(request, 'home/cart.html')
# def product_detail(request, name):
#     model = product
#     queryset = product.objects.all()
#     context_name = 'products'
#     qs = super().get_queryset()
#     if 'category' in kw
#     return render(request, 'home/product.html', {'product':product})
# def remove_from_cart(request, pk):
#     productd = cart.objects.all()
#     cart = cart(request)
#     cartd = cart.objects.get(id = pk)
#     cart.remove(cartd)
#     return redirect('cart')
#     return render(request, 'home/cart.html', {'productd':productd})
def search(request):
    query = request.GET.get('query')
    # query = form.cleaned_data.get('query', '')
    results = []
    if query:
        # Sử dụng Q objects và icontains để tìm kiếm sản phẩm
        results = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
    context = {
        # 'form': form,
        'query': query,
        'results': results
    }
    if query:
        results = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    else:
        results = None
    return render(request, 'home/search.html', {'results': results})
def remove_from_cart(request, pk):
    cart = cart(request)
    cart.remove(str(pk))
    return redirect('cart')
def out(request):
    if request.method == 'POST':
        username = request.POST['username'] # truyền thông tin theo phương thức post
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email ,password)
        user.save()
        return render(request, 'home/login.html')
    else:
        return render(request, 'home/signup.html')
    return render(request, "home/checkout.html")
def orders(request, pk):
    order = product.objects.get(id=pk)
    return render(request, 'home/order.html', {'order':order})
    if request.method == 'POST':
        name = request.POST['name'] # truyền thông tin theo phương thức post
        email = request.POST['email']
        adsresss = request.POST['address']
        city = request.POST['city']
        state = request.POST['state']
        zipcode = request.POST['zipcode']
        user = User.objects.create_user(username, email ,password)
        user.save()
        
        return render(request, 'home/order.html', {'order':order})
    else:
        return render(request, 'home/index.html')
    return render(request, "home/order.html")

website/home/templates/home/cart.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <title>Fashion-shop</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700"> 
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">


    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
  </head>
  <body>
  
  <div class="site-wrap">
    <header class="site-navbar" role="banner">
      <div class="site-navbar-top">
        <div class="container">
          <div class="row align-items-center">

            <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
              <form action="" class="site-block-top-search">
                <span class="icon icon-search2"></span>
                <input type="text" class="form-control border-0" placeholder="Search">
              </form>
            </div>

            <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
              <div class="site-logo">
                <a href="{% url 'home:home' %}" class="js-logo-clone">
                  <img src="https://levents.asia/wp-content/uploads/2021/10/logo.png" alt="">
                </a>
              </div>
            </div>

            <div class="col-6 col-md-4 order-3 order-md-3 text-right">
              <div class="site-top-icons">
                <ul>
                  <li><a href="#"><span class="icon icon-person"></span></a></li>
                  <li><a href="#"><span class="icon icon-heart-o"></span></a></li>
                  <li>
                    <a href="{% url 'home:cart' carts.id %}" class="site-cart">
                      <span class="icon icon-shopping_cart"></span>
                      <span class="count">2</span>
                    </a>
                  </li> 
                  <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                </ul>
              </div> 
            </div>

          </div>
        </div>
      </div> 
      <nav class="site-navigation text-right text-md-center" role="navigation">
        <div class="container">
          <ul class="site-menu js-clone-nav d-none d-md-block">
            <li class="has-children">
              <a href="{% url 'home:home' %}">Cửa hàng</a>
              <ul class="dropdown">
                <li><a href="#">Menu One</a></li>
                <li><a href="#">Menu Two</a></li>
                <li><a href="#">Menu Three</a></li>
                <li class="has-children">
                  <a href="#">Giảm giá</a>
                  <ul class="dropdown">
                    <li><a href="#">Menu One</a></li>
                    <li><a href="#">Menu Two</a></li>
                    <li><a href="#">Menu Three</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li class="has-children">
              <a href="about.html">Về chúng tôi</a>
              <ul class="dropdown">
                <li><a href="#">Menu One</a></li>
                <li><a href="#">Menu Two</a></li>
                <li><a href="#">Menu Three</a></li>
              </ul>
            </li>
            <li class="active"><a href="{% url 'home:shop' %}">Bộ sưu tập</a></li>
            <li><a href="#">Tuyển dụng</a></li>
            <li><a href="#">Chăm sóc khách hàng</a></li>
            <li><a href="contact.html">Liên hệ</a></li>
          </ul>
        </div>
      </nav>
    </header>

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{% url 'home:home' %}">Cửa hàng</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Cart</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <form class="col-md-12" method="post">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="product-thumbnail">ảnh</th>
                    <th class="product-name">Tên</th>
                    <th class="product-price">Gía</th>
                    <th class="product-quantity">Số lượng</th>
                    <th class="product-total">Tổng tiền</th>
                    <th class="product-remove">Xoá</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="product-thumbnail">
                      <img src="https://levents.asia/wp-content/uploads/2023/03/z4235417969997_c3419dc7733f887580dd146c3ae3480e-150x150.jpg" alt="Image" class="img-fluid">
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">
                        Levents® Aquarium Tee/ Black</h2>
                    </td>
                    <td>300.000đ</td>
                    <td>
                      <div class="input-group mb-3" style="max-width: 120px;">
                        <div class="input-group-prepend">
                          <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                        </div>
                        <input type="text" class="form-control text-center" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                        <div class="input-group-append">
                          <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                        </div>
                      </div>

                    </td>
                    <td>300.000đ</td>
                    <td><a href="#" class="btn btn-primary btn-sm">X</a></td>
                  </tr>

                  <tr>
                    <td class="product-thumbnail">
                      <img src="https://levents.asia/wp-content/uploads/2023/03/z4235417969997_c3419dc7733f887580dd146c3ae3480e-150x150.jpg" alt="Image" class="img-fluid">
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">
                        Levents® Aquarium Tee/ Black</h2>
                    </td>
                    <td>300.000đ</td>
                    <td>
                      <div class="input-group mb-3" style="max-width: 120px;">
                        <div class="input-group-prepend">
                          <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                        </div>
                        <input type="text" class="form-control text-center" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                        <div class="input-group-append">
                          <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                        </div>
                      </div>

                    </td>
                    <td>300.000đ</td>
                    <td><a href="#" class="btn btn-primary btn-sm">X</a></td>
                  </tr>
                 
                  <form action="#" method="post">
                  <tr>
                    <td class="product-thumbnail">
                      <img src="{{carts.imageURL}}" alt="Image" class="img-fluid">
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">
                        {{carts.name}}</h2>
                    </td>
                    <td>{{carts.price}}</td>
                    <td>
                      <div class="input-group mb-3" style="max-width: 120px;">
                        <div class="input-group-prepend">
                          <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                        </div>
                        <input type="text" class="form-control text-center" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                        <div class="input-group-append">
                          <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                        </div>
                      </div>

                    </td>
                    <td>{{carts.price}}</td>
                  
                    <td><a href="#" class="btn btn-primary btn-sm">X</a></td>
                  </tr>
                </form>
                
                </tbody>
              </table>
            </div>
          </form>
        </div>
        
        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6 mb-3 mb-md-0">
                <button class="btn btn-primary btn-sm btn-block">Update Cart</button>
              </div>
              <div class="col-md-6">
                <button class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</button>
              </div>
            </div>
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Giỏ hàng</h3>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-md-6">
                    <span class="text-black">Tổng tiền</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">500.000đ</strong>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <button class="btn btn-primary btn-lg py-3 btn-block" >
                      <a href="{% url 'home:order' carts.id %}">Thanh Toán</a> </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
      </div>
    </div>

    <footer class="site-footer border-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <div class="row">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">VỀ CHÚNG TÔI</h3>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Tất cả</a></li>
                  <li><a href="#">New Arrival</a></li>
                  <li><a href="#">Our Wear</a></li>
                  <li><a href="#">Phụ kiện</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Áo</a></li>
                  <li><a href="#">Quần</a></li>
                  <li><a href="#">Jacket</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Liên hệ</a></li>
                  <li><a href="#">Tuyển dụng</a></li>
                  <li><a href="#">CSKH</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            <h3 class="footer-heading mb-4">Promo</h3>
            <a href="#" class="block-6">
              <img style="width: 200px;" src="https://levents.asia/wp-content/uploads/2023/02/logoSaleNoti-1.png" alt="Image placeholder" class="img-fluid rounded mb-4" />
              <h3 class="font-weight-light mb-0">
                Mä só thuê: 41J8031547
              </h3>
              <p>Ngày cấp: 06/07/2021</p>
            </a>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">
                  842 Sư Vạn Hạnh, Phường 12, Quận 10, HCM
                </li>
                <li class="phone">
                  <a href="tel://23923929210">1900 633 028</a>
                </li>
                <li class="email">business@levents.asia</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>
    
  </body>
</html>

website/home/templates/home/checkout.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<a href="{% url 'home:order' %}">
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue"></a>
				</form>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">

			</div>
		</div>
	</div>
{% endblock body %}

website/home/templates/home/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700" />
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/aos.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/loginStyle.css' %}" />
    <!-- <title>  Document  </title> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
</head>

<body>
    
    
    <div class="wrapper">
        <div class="title">Đăng nhập ngay</div>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'home:login' %}" method="post">
            {% csrf_token %}
            <div class="field">
                <input name="username" type="text" required >
                <label>Email Address</label>
            </div>
            <div class="field">
                <input name="password" type="password" required>
                <label>Password</label>
            </div>
            <div class="content">
                <div class="checkbox">
                    <input type="checkbox" id="remember-me">
                    <label style="margin-top: 10px;" for="remember-me">Ghi nhớ tài khoảng</label>
                </div>
                <div class="pass-link"><a href="#">Forgot password?</a></div>
            </div>
            <div class="field">
                <input href="{% url 'home:home' %}" type="submit" value="Login">
            </div>
            <div class="signup-link">Chưa có tài khoảng <a href="{% url 'home:logup' %}">Đăng ký ngay</a></div>
            <div class="signup-link"><a href="{% url 'home:home' %}">Trở về cửa hàng</a></div>
            
           
        </form>
    </div>

</form>
</body>

</html>

website/home/templates/home/product.html
{% extends 'home/base.html' %}
{% block body %}
<div>
    <img src="{{product.image}}" alt="">
</div>
<h1>{{product.name}}</h1>
<p>{{product.price}}</p>
<p>{{descripyion}}</p>
{% endblock %}

website/home/templates/home/signup.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700" />
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/aos.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/signupStyle.css' %}" />
    <title>Document</title>

</head>

<body>
    <div class="wrapper">
        <div class="title">Đăng Ký Ngay</div>
        <form action="{% url 'home:logup' %}" method="POST">
            {% csrf_token %}
            <div class="field">
                <input type="text" name="username" required>
                <label for="">username</label>
            </div>
            <div class="field">
                <input name="email" type="text" required>
                <label>Email Address</label>
            </div>
            <div class="field">
                <input name="password" type="password" required>
                <label>Password</label>
            </div>
            <div class="field">
                <input  type="password" required>
                <label>Comfirm Password</label>
            </div>
            <div class="content">
                <div class="checkbox">
                    <input type="checkbox" id="remember-me">
                    <label style="margin-top: 10px;" for="remember-me">Đồng ý với điều khoảng</label>
                </div>
                
            </div>
            <div class="field">
                <input type="submit" value="Tạo tài khoản">
            </div>
            <div class="signup-link">Đã có tài khoản <a href="{% url 'home:login' %}">Đăng nhập ngay</a></div>
            <div class="signup-link"><a href="{% url 'home:home' %}">Trở về cửa hàng</a></div>
        </form>
    </div>
</body>

</html>